### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AcidOctane** [AcidOctane/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by artemsydorenko** [comment]
# Conception & Birth

Peter **was born**, when his biological father, **Mickey McFinnagin** took his then-girlfriend, (Peter's mother), **Thelma** to **an extreme bull fighting show**. At the show, Mickey took Thelma into the port-a-potty with her and knocked her up, impregnatig her with Peter, and then left the day after, never calling her again. Months later, Thelma decided to get an **abortion**, so she went to Mexico, to have the illegal prodecure done at Embryo Bell. However, at this point in the pregnancy, the baby was **too developed** and it was too late for an abortion, despite her only being pregnant for six months and Peter was prematurely born there on the spot. When Thelma saw her newborn child, she thought he was **beautiful and wanted** to raise him and care for him, so he could live a full life. So, she went back to America. However, she was too embarassed about what happened to tell anyone about it, so she never filled out the proper files to legally make **Peter** into an American citizen, so he technically remained **an illegal immigrant** for most of his life.
Not wanting Peter to grow up without a father, Thelma married **Francis Griffin** and passed him off as Peter's biological father, throughout his entire childhood, **not telling** Peter the actual **truth**.

# Childhood

As a child, Peter was raised by Thelma and Francis Griffin.
Tthe ghost of Patrick Swayze took Peter back to a Christmas, when Peter was **5 years old**.
When Peter was **6 years old**, Thelma gave birth to his **sister**, **Karen Griffin**, who would always abuse and bully him.

# Teenage Years

Peter attended **Buddy Cianci Junior High School** as a middle schooler and attended **Providence High School** as a high schooler.
During his high school years, Peter and **his friend**, **Cleveland**, got a part-time job, working as a **towel boy** for the rich pricks in Newport, where he was mistreated by the workers and sorrowfully underpaid. There, he met **Lois** for the first time. He **fell in love** with her and became her friend, much to the disapproval of Carter Pewterschmidt, who only wanted Lois to go out with rich white people from Newport. During high school, **Glenn Quagmire** was the **love rival** of Peter, who was also courting Lois and if it wasn't for Peter, Lois would have married Quagmire.

# Adulthood

**Peter**, **Cleveland**, and **Quagmire** were **friends** in high school. Though Peter didn't first meet Quagmire until he was rescued by him as a college student and didn't meet Cleveland until shortly after that when Cleveland picked him up in his van after leaving Stoolbend, Virginia.

# College Years
Peter was in college, when he first started noticing breasts developing on women. At this time, Peter also started developing man boobs.  Peter met Lois before college and never had the chance to go crazy with the college girls.

# Marriage to Lois

Despite **never** winning the **approval** of **Carter and Babs Pewterschmidt**, Peter still married Lois, as the latter gave her approval.  One thing is for certain, however. Peter married Lois in the '90s, much to the disapproval of the latter's parents, as well as Peter's father and as for Peter and Lois, it was the **happiest day** of both of their lives.

# Becoming a Dad
Together, Peter and Lois have three children, **Chris**, **Meg**, and baby **Stewie**. After a mix up at a sperm bank, Peter also became the biological father of **Bertram**. In addition, he and Lois had a child named Peter Griffin Jr. who died when Peter shook him too much. Out of pity he also **adopted** an **intellectual talking dog** named **Brian** who formerly lived on the street as a stray.

# Present Day

**Peter Griffin** is a man in his mid to late '40s, being a loud, destructive **idiot**, who serves as a terrible **dad** and lousy **husband**.

# Employment History

Peter worked at the **Happy-Go-Lucky Toy Factory** for the bizarre Mr. Weed. But when Mr. Weed was accidentally killed by choking on a dinner roll in "Mr. Saturday Knight", Peter was **out of a job** and had to find work elsewhere.

Peter bought a fishing **boat**, which he named **The S.S. More Powerful Than Superman, Batman, Spider-Man, and The Incredible Hulk Put Together** and found work at a **small independent fishing business**, run by a man named Hennessey O'Callaghan. During a desperate attempt to catch more fish at a private island, Peter's boat is destroyed by a hurricane. Despite surviving the hurricane, with the loss of his boat, Peter is again **jobless**.

Peter goes to the **unemployment office**, and obtains a job at **the Pawtucket Brewery**. Initially he is placed on the **line**, but after over-indulging in the free ale, he is demoted to the **shipping department,** working with Opie and under Angela. To date, this has been his longest-lasting job. Angela was also his longest-lasting boss.

After Angela deceased, he still worked there. What changed about his job is that Angela's position was taken over by not one but two new bosses named **Bert and Sheila**, an interracial married couple, who were **even more crazy and annoying than Peter**, himself, putting a fresh new twist on his job, by making him the one who gets annoyed by his bosses instead of the other way around, as was the case with all three of his previous bosses.

## Peter's Bosses

- Mr. Weed
- Hennessey O'Callaghan
- Angela
- Bert/Sheila

# Elder Years

Stewie time travels to the future to see Peter Griffin, now as a retired senior citizen, living alone with Lois. However, the timeline that this future takes place in is null and void, due to events in the present making it impossible for this future to exist. These events include Stewie losing his virginity and Francis dying. These things make this future impossible, so there has to be another timeline now.

# Death

The ghost of Patrick Swayze showed Peter what his future would be like if he continued to ignore and disrespect his family on Christmas. He took him to the graveyard, where Peter's tombstone sat. Peter's cause of death was getting incinerated when a porn star lit a cigarette in his house, which caught his very dry Christmas tree on fire and later burned down his whole house with him in it. A very elderly Brian Griffin slept at the foot of his coffin. Peter changed his actions to avoid this future ever happening, so it's not likely this is how he will die.
