### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AcidOctane** [AcidOctane/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by artemsydorenko** [comment]
# Appearance

Peter Griffin is a fat, overweight guy who stands at 6'0" and weighs 270 lbs. He has short cut brown hair and a big fat head which has become one with his neck. He has big, round eyes and a round nose, and a big mouth. His chin has a very large and deep cleft in it, making the rest of his chin very big and rounded. He wears glasses which are very thin and are the exact same shape and size as his eyeballs, making them pretty invisible at most times. He wears a white buttoned shirt with a collar and slightly rolled up sleeves. He also has green pants and a black belt with a golden buckle. He also has dark brown shoes.
Peter Griffin's eye color is green.
Peter Griffin had a miniature vestigial twin that was buried under the flesh of his shoulder. His vestigial twin was named Chip Griffin and he basically looked like a miniature version of himself with a chubbier head and somehow, glasses despite being trapped under his skin for all those years. Chip was surgically removed and sent away.

**Comment by artemsydorenko** [comment]
# Personality

An I.Q. test confirms that his low intellect places him in a category below mentally retarded. He rushes off to attend Quahog College just to count to three. His mental shortcomings have resulted in various accidents to other people; most notably the death of his step-father Francis Griffin, and injuries on multiple occasions to his wife Lois. His attention span is also incredibly short. When he discovered his mental retardation, he closed his eyes while driving, wishing "it would all be over" and hitting Tom Tucker with his car instead. Given his short attention span, as well as his erratic and frequently inappropriate behavior, it is conceivable that Peter suffers from Attention Deficit Hyperactivity Disorder, or ADHD. In addition, Peter is often seen getting hurt mostly by his own fault. When trying to impress Chris with his forward-thinking, Peter claims it is still 1988.

He is incredibly jealous of other attractions Lois has in her life, an attitude that tends to get out of hand in most cases; he goes so far as to punch his reflection in the mirror after Lois comments on it being handsome. He tells Lois, 

> Remember what I always tell you, if I come home in the middle of the day and catch you having sex with someone, I'll kill you both 

though when he catches her in bed with Bill Clinton, he takes no hostile actions whatsoever. However, he seems not to mind the fact that she slept with other men before they met, just so long as she doesn't do so again; he is particularly proud of the fact that she once slept with Gene Simmons of Kiss when he discovers this, but forbids any sexual activity between the two now .

Among the members of his family, he tends to treat Meg with the least respect;  he reminisces about the various pranks he played on her, including tripping her, flicking her nose with his finger, and even shooting her at one point. Also, he wipes a boogie on her hat saying

> Hey Meg...proud of you

He is known to embarrass her at times and with things that mean the most to Meg; the entire family once huddled together to read her diary and continue after Meg catches them.

**Comment by artemsydorenko** [comment]
# Intelligence
Peter Griffin has undeniably proven to be a complete idiot. He is making stupid, unintelligent comments followed by him performing a ridiculous action. He never learns from his mistakes and will always go right back to doing them again. All in all, he's your everyday comedic idiot and definitely falls under the "stupid" category.

Looking deeper into Peter's stupidity, we can see that most of his brainless behavior seems to be done out of immaturity. At times he demonstrates the intelligence level of a teenage boy in his "jackass" phase, pulling off dumb and dangerous stunts that only get him hurt and at other times, he acts like a four year old boy, taking on the personality of a little kid perfectly.

Peter never passed the third grade. Despite having not passed the third grade, he was seen passing the fourth grade. Also, there's been a lot of flashbacks to him in middle school and high school and college, so I guess it's reasonable to say that even though he never technically passed those grades, the school board still let him move on to other grades and he can just go back to those classes and waste his time on school whenever he wants.

Peter has shown some sparks of being smarter than those around him, when James Woods returns to get revenge, Peter and Brian get rid of him exactly the same way they did the first time, using a box and trail of candy, he makes a point that next time Woods shows up they should do that in the beginning as he has already fallen for it twice.

Peter does have ideas he thinks are smart but often back fire, such as when he got his new drivers license he decided to have the picture taken when he was drunk, so if a cop pulled him over for DUI when he looked at his license he would think he was just fine.

Also despite being married to Lois for 20 years, he was unable to realize she was in danger  despite her acting very odd. As well as was more interested in listening to his songs than to pay any real attention. He also firmly believed that Derek Wilcox was a God due to the fact the picture on his phone made him look as if he was holding up the Hollywood sign, despite Derek clearing explaining to him it was merely a camera trick.

**Comment by artemsydorenko** [comment]
# Relationships
## Family

**_Lois Griffin_** - Peter is the husband of Lois. Lois loves Peter because he's so delightful, funny, and cheery and he makes everybody happy just with his joyous nature alone. Although Peter will occasionally drive Lois nuts with his crazy antics and nonsensical behavior, she still loves him and he still loves her. When the show went through seasonal rot, this all changed, where the new formula of the shoe was Peter drives Lois crazy by being an obnoxious idiotic husband who doesn't respect and cherish her and treats her like shit and she still stays with him for no reason.

**_Chris Griffin_** - Peter is the father of Chris, who teaches his son a bunch of valuable life lessons like which way to lean while he farts. Chris has kind of fallen in his father's footsteps and become a fat dumbass like him. It's obvious that he's gunna be just like him when he grows up.

**_Meg Griffin_** - Peter abuses Meg all the time by farting in her face and telling her to shut up, via his famous catchphrase, 

> Shut up, Meg.



**_Stewie Griffin_** - Peter is the father of Stewie and he doesn't understand what he says. Their interactions are generally meaningless, but Peter treats Stewie like a regular baby and that's all.

**_Brian Griffin_** - Peter owns Brian as his pet dog. Brian is the voice of reason to how stupid Peter is. He is his very best friend.

##Friends

**_Beer Bar Buddies_** - Aside from Brian, Peter's best friends are Glenn Quagmire, Joe Swanson, Cleveland Brown and Jimmy Wendell Colton VII. They enjoy hanging out at their local bar, The Drunken Clam, drinking and chewing the fat. The four men do many things together. Once the four friends entered and won a costume contest at an 80s TV convention, dressing up as the A-Team. On another occasion, their fishing boat was wrecked, and they were stranded together on a desert island.

**_Glenn Quagmire 
Cleveland Brown
Joe Swanson
Bonnie Swanson 
Horace 
Jerome Cool J 
Mort Goldman 
Muriel Goldman 
Seamus Levine 
Tom Tucker 
Elmer Hartman 
Bruce 
Consuela De La Morrela 
Dave Campbell 
Dotty Campbell 
Jillian Russel-Wilcox 
Ida Davis 
Death 
Jesus Christ_**

## Enemies

**_Giant Chicken_** - the feud starts over a trivial incident where the chicken gives Peter an expired coupon at the grocery store. The chicken is identified as "Ernie", and he has a wife named Nicole, also a giant chicken. Peter is invited to dinner with them after they realize that their fighting is pointless, but then they argue over who will pay the bill, and the fighting starts all over again. Ernie makes a brief, non-fighting appearance, in which Peter unwittingly assaults the giant chicken at a 90s dance, retroactively providing Ernie with a grudge against Peter. Ernie was also mentioned when Peter was hospitalized due to kidney failure, Brian offered to give Peter his kidney. In response to the family's shock, Dr. Hartman stated that this transplant was not the only crazy thing that took place in medical research, and said that he once attempted to clone a chicken. This resulted in the original chicken to grow human-sized, violent, and incredibly hostile.

**_James Woods
Homer Simpson
Donald Trump_**

**Comment by artemsydorenko** [comment]
# Health
Despite being obese, a heavy drinker, and accident-prone, Peter appears to be in great health. Periodically, Peter is shown recovering quickly from serious injuries, such as losing all the fingers on his right hand while handling M-70 firecrackers. In spite of the injury, he has no visible scarring on his hand. He displays enormous strength, such as when single handedly challenging a professional football team in "Patriot Games". Peter played high school football and his sister mentions his wearing a bra while playing.

Peter asserts that he weighs 399lbs, the same as he did in grade school. During Peter's "poop montage", he loses over 50 pounds; going from around 430 lbs to 360 lbs.

He underwent a vasectomy.

Occasionally Peter soils himself. After these accidents, he never seems to notice that it was a result of his own behavior.

Peter has used various drugs such as LSD, Meth, "ecstasy", marijuana, steroids, cocaine, and crack cocaine, but has managed to avoid incarceration and long-term effects from the use of these drugs.

After eating thirty hamburgers in one sitting, Peter suffered a stroke that paralyzed the left side of his body. For the next three months he walked with a limp, his arm and leg hung lifelessly from his body, and his eye and part of his mouth had slid down his face, giving him a speech impediment. This damage was reversed completely after a five minute session at a stem cell research facility.

Peter's mass causes him to have his own gravitational pull, shown when Brian threw an apple, a glass of water, a book and a Television, which immediately started to orbit his body.

Peter used to smoke. 

Peter as a child was never immunized for the mumps.

Peter suffers a kidney failure from a homemade energy drink. Brian offers do donate his kidneys, which would kill him. Before the surgery, Dr. Hartman offers to give up one of his kidneys, which he does and reveals that Brian's kidneys could not have been transferred to Peter's body.

Peter's estranged sister Karen Griffin visits for Thanksgiving  and reveals several personal details to his friends, including that when upset, he stutters and pees his pants.

**Comment by artemsydorenko** [comment]
# Car

Peter's car strongly resembles a 1977 Ford LTD Station Wagon although no specific brand has been mentioned and  there is a remark about it having a flip-down TV in a mid-'81s station wagon.

**Comment by s1dneyoctane** [comment]
APPEARANCE
Peter Griffin is a fat, overweight guy who stands at 6'0" and weighs 270 lbs.
He has short cut brown hair and a big fat head which has become one with his neck.
He has big, round eyes and a round nose, and a big mouth.
His chin has a very large and deep cleft in it, making the rest of his chin very big and rounded.
He wears glasses which are very thin and are the exact same shape and size as his eyeballs, making them pretty invisible at most times.
He wears a white buttoned shirt with a collar and slightly rolled up sleeves.
He also has green pants and a black belt with a golden buckle. He also has dark brown shoes.
Peter Griffin's eye color is green.
Peter Griffin had a miniature vestigial twin that was buried under the flesh of his shoulder. His vestigial twin was named Chip Griffin and he basically looked like a miniature version of himself with a chubbier head and somehow, glasses despite being trapped under his skin for all those years. Chip was surgically removed and sent away.

**Comment by s1dneyoctane** [comment]
PERSONALITY
An I.Q. test confirms that his low intellect places him in a category below mentally retarded.
He rushes off to attend Quahog College just to count to three.
His mental shortcomings have resulted in various accidents to other people; most notably the death of his step-father Francis Griffin, and injuries on multiple occasions to his wife Lois.
His attention span is also incredibly short. When he discovered his mental retardation, he closed his eyes while driving, wishing "it would all be over" and hitting Tom Tucker with his car instead.
Given his short attention span, as well as his erratic and frequently inappropriate behavior, it is conceivable that Peter suffers from Attention Deficit Hyperactivity Disorder, or ADHD.
In addition, Peter is often seen getting hurt mostly by his own fault. When trying to impress Chris with his forward-thinking, Peter claims it is still 1988.
He is incredibly jealous of other attractions Lois has in her life, an attitude that tends to get out of hand in most cases; he goes so far as to punch his reflection in the mirror after Lois comments on it being handsome. He tells Lois,
"Remember what I always tell you, if I come home in the middle of the day and catch you having sex with someone, I'll kill you both""
though when he catches her in bed with Bill Clinton, he takes no hostile actions whatsoever.
However, he seems not to mind the fact that she slept with other men before they met, just so long as she doesn't do so again; he is particularly proud of the fact that she once slept with Gene Simmons of Kiss when he discovers this, but forbids any sexual activity between the two now .
Among the members of his family, he tends to treat Meg with the least respect; he reminisces about the various pranks he played on her, including tripping her, flicking her nose with his finger, and even shooting her at one point. Also, he wipes a boogie on her hat saying
"Hey Meg...proud of you"
He is known to embarrass her at times and with things that mean the most to Meg; the entire family once huddled together to read her diary and continue after Meg catches them.
